### ISSUE TITLE
Add the support of typst

### ISSUE THREAD

**Issue by yodatak** [vitallium/zed-ltex#1]
Hello thanks for your extension i love it when i use latex and markdown i want to use more typst

**Comment by vitallium** [comment]
@yodatak There is an extension for `typst` - [extensions/typst](https://github.com/WeetHet/typst.zed/tree/821a4d9d683d4ff095dd3f0b59f980db96f939a1)

**Comment by yodatak** [comment]
@vitallium 
Yes but not for orthography correction

**Comment by vitallium** [comment]
> @vitallium Yes but not for orthography correction

@yodatak Could you please share a bit more detail? I'm having a little trouble understanding.

**Comment by yodatak** [comment]
yes sure i would love to use this extention to correct typography error and orthography error of typst file is possible with your extention ? ( sorry to not be as clear as i want )

**Comment by vitallium** [comment]
> yes sure i would love to use this extention to correct typography error and orthography error of typst file is possible with your extention ? ( sorry to not be as clear as i want )

Ah, sorry, I completely misunderstood you! I thought you wanted to add LSP for Typst files but you are asking about enabling `ltex` in Typst files.

**Comment by vitallium** [comment]
Added it in https://github.com/vitallium/zed-ltex/commit/163be4c03f8e3c6a4ff986e22540f394062b8f49
