### ISSUE TITLE
Add option to change language

### ISSUE THREAD

**Issue by TheRepSter** [vitallium/zed-ltex#2]
At the VSCode extension for LTeX, there is a setting to change the language from English to others (like Spanish or Catalan).

Exists that option on this extension? If not, maybe could be good implementing it.

Thanks in advance.

**Comment by TheRepSter** [comment]
Nvm, I just found out how. Sorry. 

at settings.json
```json
"lsp": {
  "ltex": {
    "settings": {
      "ltex": {
        "language": "ca-ES"
      }
    }
  }
}
```
For example. Any ltex.[setting] at vscode works, or at leasts seems to.

**Comment by vitallium** [comment]
@TheRepSter Oh, that's great! I will add that to the README.md to make it easier for everyone to find. Thanks!
